### ISSUE TITLE
Responsive Web Design Projects

### ISSUE THREAD

**Issue by maria1186** [stefaniedev/freecodecamp-coursework#9]
I solved the challenges, made the 5 pages, but they are not reported as solved. What should I do to account for these tasks being done?

**Comment by stefaniedev** [comment]
Do you still need help with this? It didn't show until now for some reason. Usually you have to put your code in codepen and go through the test suites then enter the codepen link on your freecodecamp assignment page. Hope this helps!

**Comment by maria1186** [comment]
I changed from Google Chrome to Mozilla and the problem is fixed. Thanks for the reply.

**Comment by stefaniedev** [comment]
Oh cool sorry it took so long GitHub didn't notify me! Weird since they say to use chrome usually in all the projects!
